stock_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: REQMULU-VGC17805   # e.g. abc12345.us-east-1
      user: TaewonYu17
      password: dotxyr=jaczup=totSo6
      role: SYSADMIN
      warehouse: STOCK_WH
      database: STOCK_DB
      schema: RAW
      threads: 4